apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: dapr-config
spec:
  # tracing 비활성화 (Zipkin 미사용)
  # tracing:
  #   samplingRate: "1"
  features:
    - name: Actor
      enabled: true
